# Generated by Django 3.0.6 on 2020-05-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
                ('event_date', models.CharField(max_length=200)),
                ('event_remarks', models.CharField(max_length=200)),
                ('pricing', models.CharField(max_length=200)),
                ('date_added', models.DateField()),
            ],
        ),
    ]
