# Generated by Django 3.0.6 on 2020-05-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='pricing',
            new_name='event_pricing',
        ),
    ]
