# Generated by Django 3.0.6 on 2020-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0003_auto_20200518_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='event_date',
            field=models.CharField(max_length=200),
        ),
    ]
