# Generated by Django 3.0.6 on 2020-05-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0004_auto_20200518_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='event_date',
            field=models.DateField(),
        ),
    ]
