# Generated by Django 3.0.6 on 2020-05-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0005_auto_20200518_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='event_date',
            field=models.CharField(max_length=200),
        ),
    ]
