# Generated by Django 3.0.6 on 2020-05-18 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0006_auto_20200518_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
