# Generated by Django 3.0.6 on 2020-05-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0007_auto_20200518_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='event_remarks',
            field=models.TextField(),
        ),
    ]
