# Generated by Django 3.0.6 on 2020-05-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_monitoring_system', '0008_auto_20200518_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='event',
        ),
    ]
